[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"
[project]
name = "chat_weboscket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "aiosqlite>=0.22.1",
    "greenlet>=3.3.0",
    "sqlalchemy>=2.0",
    "websockets>=15.0.1",
    "mypy>=1.19.1",
    "pyright",
]
[projects.scripts]
chat-websocket = "server:main_wrap"
[tool.setuptools]
py-modules = ["server"]
